name: Daily Commits

on:
  schedule:
    - cron: '0 12 * * *'  # UTC

jobs:
  daily-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "proales"
        git config --global user.email "proales@proales.com"

    - name: Create and push daily commit
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        chmod +x daily_commits.sh
        ./daily_commits.sh
